export const mockFirstLetter = {
  drinks: [
    {
      idDrink: '12518',
      strDrink: 'Whisky Mac',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Collins Glass',
      strInstructions: 'Pour both of the ingredients into a wine goblet with no ice.',
      strInstructionsES: null,
      strInstructionsDE: 'Beide Zutaten in einen Weinkelch geben, ohne Eis.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare entrambi gli ingredienti in un calice da vino senza ghiaccio.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yvvwys1461867858.jpg',
      strIngredient1: 'Scotch',
      strIngredient2: 'Wine',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '1 oz Green Ginger ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-04-28 19:24:18',
    },
    {
      idDrink: '17194',
      strDrink: 'White Lady',
      strDrinkAlternate: null,
      strTags: 'IBA,Classic',
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: 'Unforgettables',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions: 'Add all ingredients into cocktail shaker filled with ice. Shake well and strain into large cocktail glass.',
      strInstructionsES: null,
      strInstructionsDE: 'Alle Zutaten in den mit Eis gefüllten Cocktailshaker geben. Gut schütteln und in ein großes Cocktailglas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'Aggiungere tutti gli ingredienti in uno shaker pieno di ghiaccio.Shakerare bene e filtrare in una coppetta da cocktail grande.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/jofsaz1504352991.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Triple Sec',
      strIngredient3: 'Lemon Juice',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '4cl',
      strMeasure2: '3cl',
      strMeasure3: '2cl',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 12:49:52',
    },
  ] };
