export const mockFirstLetterMeals = {
  meals: [
    {
      idMeal: '52776',
      strMeal: 'Chocolate Gateau',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'French',
      strInstructions: 'Preheat the oven to 180°C/350°F/Gas Mark 4. Grease and line the base of an 8 in round spring form cake tin with baking parchment\r\nBreak the chocolate into a heatproof bowl and place over a saucepan of gently simmering water and stir until it melts. (or melt in the microwave for 2-3 mins stirring occasionally)\r\nPlace the butter and sugar in a mixing bowl and cream together with a wooden spoon until light and fluffy. Gradually beat in the eggs, adding a little flour if the mixture begins to curdle. Fold in the remaining flour with the cooled, melted chocolate and milk. Mix until smooth.\r\nSpread the mixture into the cake tin and bake for 50-55 mins or until firm in the centre and a skewer comes out cleanly. Cool for 10 minutes, then turn out and cool completely.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tqtywx1468317395.jpg',
      strTags: 'Cake,Chocolate,Desert,Pudding',
      strYoutube: 'https://www.youtube.com/watch?v=dsJtgmAhFF4',
      strIngredient1: 'Plain chocolate',
      strIngredient2: 'Butter',
      strIngredient3: 'Milk',
      strIngredient4: 'Eggs',
      strIngredient5: 'Granulated Sugar',
      strIngredient6: 'Flour',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '250g',
      strMeasure2: '175g',
      strMeasure3: '2 tablespoons',
      strMeasure4: '5',
      strMeasure5: '175g',
      strMeasure6: '125g',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: 'http://www.goodtoknow.co.uk/recipes/536028/chocolate-gateau',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52765',
      strMeal: 'Chicken Enchilada Casserole',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Mexican',
      strInstructions: 'Cut each chicken breast in about 3 pieces, so that it cooks faster and put it in a small pot. Pour Enchilada sauce over it and cook covered on low to medium heat until chicken is cooked through, about 20 minutes. No water is needed, the chicken will cook in the Enchilada sauce. Make sure you stir occasionally so that it doesn\'t stick to the bottom.\r\nRemove chicken from the pot and shred with two forks.\r\nPreheat oven to 375 F degrees.\r\nStart layering the casserole. Start with about ¼ cup of the leftover Enchilada sauce over the bottom of a baking dish. I used a longer baking dish, so that I can put 2 corn tortillas across. Place 2 tortillas on the bottom, top with ⅓ of the chicken and ⅓ of the remaining sauce. Sprinkle with ⅓ of the cheese and repeat starting with 2 more tortillas, then chicken, sauce, cheese. Repeat with last layer with the remaining ingredients, tortillas, chicken, sauce and cheese.\r\nBake for 20 to 30 minutes uncovered, until bubbly and cheese has melted and started to brown on top.\r\nServe warm.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg',
      strTags: 'Casserole,Cheasy,Meat',
      strYoutube: 'https://www.youtube.com/watch?v=EtVkwVKLc_M',
      strIngredient1: 'Enchilada sauce',
      strIngredient2: 'shredded Monterey Jack cheese',
      strIngredient3: 'corn tortillas',
      strIngredient4: 'chicken breasts',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '14 oz jar',
      strMeasure2: '3 Cups',
      strMeasure3: '6',
      strMeasure4: '2',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ] };
